FROM rust:1.75-alpine AS builder

RUN apk add --no-cache g++ zlib zlib-dev git linux-headers libressl-dev libmagic libusb-dev hidapi-dev eudev-dev

WORKDIR /app
COPY . /app

ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
RUN cargo build --release --features "$(grep 'feature =' src/keyring/providers.rs | tr -d '[:blank:]' | sort | uniq | cut -d '"' -f 2 | xargs)"

FROM alpine
COPY --from=builder /app/target/release/tmkms /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/tmkms"]