#[[tx_signer]]
#chain_id = "$CHAIN_ID"
#schema = "$SCHEMA"
#account_number = 123456 # CHANGE ME!
#account_address = "cosmos1..." # CHANGE ME!
#acl = { msg_type = ["sdk/Tx"] } # CHANGE ME!
#poll_interval = { blocks = 5 }
#source = { protocol = "jsonrpc", uri = "http://127.0.0.1:23456/" } # CHANGE ME!
#rpc = { addr =  "tcp://127.0.0.1:26657" } # CHANGE ME!
#seq_file = "$KMS_HOME/state/$CHAIN_ID-account-seq.json"
