# https://github.com/RustSec/cargo-audit/blob/master/audit.toml.example

[advisories]
ignore = [
    "RUSTSEC-2019-0031",
    "RUSTSEC-2019-0036",
    "RUSTSEC-2020-0016",
    "RUSTSEC-2020-0031",
    "RUSTSEC-2020-0036",
    "RUSTSEC-2020-0071",
    "RUSTSEC-2020-0159",
    "RUSTSEC-2021-0060",
    "RUSTSEC-2021-0059",
    "RUSTSEC-2021-0064",
    "RUSTSEC-2021-0073"
] # advisory IDs to ignore e.g. ["RUSTSEC-2019-0001", ...]
