# https://github.com/RustSec/cargo-audit/blob/master/audit.toml.example

[advisories]
ignore = [
    "RUSTSEC-2019-0031",
    "RUSTSEC-2019-0036",
    "RUSTSEC-2020-0016",
    "RUSTSEC-2020-0031",
    "RUSTSEC-2020-0036"
] # advisory IDs to ignore e.g. ["RUSTSEC-2019-0001", ...]
